DAY_ONE/Controllers/ClassController.cs
using DAY_ONE.DAL;
using DAY_ONE.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using System.IO;
using iTextSharp.tool.xml;
using iTextSharp.tool.xml.html;
using iTextSharp.tool.xml.parser;
using iTextSharp.tool.xml.pipeline.css;
using iTextSharp.tool.xml.pipeline.end;
using iTextSharp.tool.xml.pipeline.html;
using System.Web.UI;
using System.Drawing;
using iTextSharp.text.pdf.codec.wmf;
using System.Text;

namespace DAY_ONE.Controllers
{
    public class ClassController : Controller
    {
        // GET: Class

        public ActionResult Names()
        {
            return View();
        }
        public ActionResult HtmltoPDF()
        {
            return View();
        }
        public ActionResult HtmltoPDF3()
        {
            return View();
        }
        public ActionResult HtmltoPDFBG()
        {
            return View();
        }
        public ActionResult HtmltoPDFWithoutBG()
        {
            return View();
        }
        //public void ExportToPDF(object sender, EventArgs e)
        //{
        //    try

        //    {

        //        string strHtml = string.Empty;

        //        string htmlFileName = Server.MapPath("~") + "\\Views\\" + "\\Class\\" + "Names.cshtml";

        //        string pdfFileName = Request.PhysicalApplicationPath + "\\Views\\" + "\\Class\\" + "ConvertHTMLToPDF.pdf";

        //        FileStream fsHTMLDocument = new FileStream(htmlFileName, FileMode.Open, FileAccess.Read);

        //        StreamReader srHTMLDocument = new StreamReader(fsHTMLDocument);

        //        strHtml = srHTMLDocument.ReadToEnd();

        //        srHTMLDocument.Close();

        //        strHtml = strHtml.Replace("\r\n", "");

        //        strHtml = strHtml.Replace("\0", "");

        //        using (Stream fs = new FileStream(Request.PhysicalApplicationPath + "\\Views\\" + "\\Class\\" + "ConvertHTMLToPDF.pdf", FileMode.Create))

        //        {

        //            using (Document doc = new Document(PageSize.A4))

        //            {

        //                PdfWriter writer = PdfWriter.GetInstance(doc, fs);

        //                doc.Open();

        //                using (StringReader sr = new StringReader(strHtml))

        //                {

        //                    XMLWorkerHelper.GetInstance().ParseXHtml(writer, doc, sr);

        //                }

        //                doc.Close();

        //                Response.ContentType = "application/pdf";

        //                Response.AddHeader("content-disposition", "attachment;filename=sample.pdf");

        //                Response.Cache.SetCacheability(HttpCacheability.NoCache);

        //                Response.Write(doc);

        //            }

        //        }

        //    }

        //    catch (Exception ex)

        //    {

        //        Response.Write(ex.Message);

        //    }


        //}

        //protected void ExportToPDF(object sender, EventArgs e)
        //{
        //    StringReader sr = new StringReader(Request.Form[hfGridHtml.UniqueID]);
        //    Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 10f, 0f);
        //    PdfWriter writer = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
        //    pdfDoc.Open();
        //    XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
        //    pdfDoc.Close();
        //    Response.ContentType = "application/pdf";
        //    Response.AddHeader("content-disposition", "attachment;filename=HTML.pdf");
        //    Response.Cache.SetCacheability(HttpCacheability.NoCache);
        //    Response.Write(pdfDoc);
        //    Response.End();
        //}

        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {


                StringReader sr = new StringReader(GridHtml);

                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 10f, 10f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "StudentDetails.pdf");
            }
        }
        //[HttpPost]
        //[ValidateInput(false)]
        //public FileResult Export(string htmlContent)
        //{
        //    using (MemoryStream stream = new System.IO.MemoryStream())
        //    {
        //        StringReader sr = new StringReader(htmlContent);
        //        Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 10f, 10f);
        //        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
        //        pdfDoc.Open();
        //        XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
        //        pdfDoc.Close();
        //        return File(stream.ToArray(), "application/pdf", "StudentDetails.pdf");
        //    }
        //}
        [HttpPost]
        public JsonResult SaveData(ClassDBModel _dbModel)
        {
            int Result = 0;
            if (_dbModel.ClassID > 0)
            {
                Result = UpdateName(_dbModel);
            }
            else
            {
                Result = SaveName(_dbModel);
            }
            if (Result > 0)
                return Json(new { Success = true });
            else
                return Json(new { Success = false });
        }

        [HttpGet]
        public JsonResult LoadAllData()
        {
            List<ClassDBModel> _dbModelList = new List<ClassDBModel>();
            _dbModelList = LoadDataFromDataSet();
            return this.Json(_dbModelList, JsonRequestBehavior.AllowGet);
        }
        private List<ClassDBModel> LoadDataFromDataSet()
        {
            List<ClassDBModel> _modelList = new List<ClassDBModel>();
            SqlConnection conn = new SqlConnection(DBConnection.GetConnection());
            conn.Open();
            SqlCommand dAd = new SqlCommand("SELECT * FROM Class ORDER BY ClassID DESC", conn);
            SqlDataAdapter sda = new SqlDataAdapter(dAd);
            dAd.CommandType = CommandType.Text;
            DataTable dt = new DataTable();
            try
            {
                sda.Fill(dt);
                if (dt.Rows.Count > 0)
                {
                    _modelList = (from DataRow row in dt.Rows
                                  select new ClassDBModel
                                  {
                                      ClassID = Convert.ToInt32(row["ClassID"].ToString()),
                                      ClassName = row["ClassName"].ToString()
                                  }).ToList();
                }
                return _modelList;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                dt.Dispose();
                dAd.Dispose();
                conn.Close();
                conn.Dispose();
            }
        }


        private int SaveName(ClassDBModel _dbModel)
        {
            SqlConnection conn = new SqlConnection(DBConnection.GetConnection());

            conn.Open();
            SqlCommand dCmd = new SqlCommand(@"INSERT INTO Class (ClassName, AddedBy)
                                              VALUES(@ClassName, @AddedBy)", conn);
            dCmd.CommandType = System.Data.CommandType.Text;

            try
            {
                dCmd.Parameters.AddWithValue("@ClassID", 0);
                dCmd.Parameters.AddWithValue("@ClassName", _dbModel.ClassName);
                dCmd.Parameters.AddWithValue("@AddedBy", "Iqbal");
                return dCmd.ExecuteNonQuery();

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                dCmd.Dispose();
                conn.Close();
                conn.Dispose();

            }
        }
        [HttpPost]
        public JsonResult DeleteSelectedClass(ClassDBModel _dbModel)
        {
            int _result = 0;
            _result = DeleteClassName(_dbModel);
            if (_result > 0)
                return Json(new { success = true });
            else
                return Json(new { success = false });
        }
        private int DeleteClassName(ClassDBModel dbModel)
        {
            SqlConnection conn = new SqlConnection(DBConnection.GetConnection());
            conn.Open();
            SqlCommand dCmd = new SqlCommand("DELETE FROM Class WHERE ClassID = @ClassID", conn);
            dCmd.CommandType = CommandType.Text;
            try
            {
                dCmd.Parameters.AddWithValue("@ClassID", dbModel.ClassID);
                return dCmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                dCmd.Dispose();
                conn.Close();
                conn.Dispose();
            }
        }

        [HttpPost]
        public JsonResult LoadSelectedClass(ClassDBModel _dbModel)
        {
            List<ClassDBModel> _dbModelList = new List<ClassDBModel>();
            _dbModelList = LoadSelectedClassName(_dbModel);
            return this.Json(_dbModelList, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Info(int ClassID, string reportTypes)
        //{
        //    try
        //    {


        //        //string reportTypes = "EXCELOPENXML";

        //        DataSet ds = new DataSet();
        //        LocalReport localReport = new LocalReport();

        //        ds = LoadAllCG01Report(ClassID);

DAY_ONE/Views/Class/HtmltoPDF.cshtml
@{
    ViewBag.Title = "HtmltoPDF";
}
<html>
<head>
</head>
<body>
    <div id="Grid"  >
        <style>
            table
            {
                font-family: arial, sans-serif;
                
                width: 100%;
                
               
            }
            th
            {
                
                padding: 8px;
                color: Black;
            }
            td
            {
               
                padding: 8px;
                color: black;
                
            }
            tr
            {
            }
            .im44
            {
                
                height: 40px;
                width: 50px;
                background-image:url("file///http://localhost:3367/UploadFile/Pakiza.png");
            }
            #testimg
            {
               
            }
            .testTable
            {
                width: 30%;
                font-weight: bold;
            }
            .divtest
            {
               background-color:Green;
            }
             .divtest2
            {
               background-color:White;
            }
            
            
        </style>
        @* <input type="text" id="GridHtml3" name="GridHtml7" />*@
        <div class="divtest">
        <div class="divtest2">
        <div>
            <p style="text-align: center; opacity:0.5" >
     
            <img src="http://localhost:3367/UploadFile/Pakiza.png" alt=""; id="testimg"; runat="server"  replace>
             <h2 style="text-align: Center; font-weight: bold">
                Pakiza Technovation Limited
            </h2>
            </p>
            <p style="text-align: right">
                Kazi Shakhawat Hossain
                <br />
                Business Automation<br />
                Pakiza Technovation Limited.
            </p>
            <h5 style="color: Black; text-align: center; font-weight: bold">
                Company's Information
            </h5>
        </div>
        <table border="1" >
            <tr style="background-color: #e8eef4">
                <th>
                    Company
                </th>
                <th>
                    Contact
                </th>
                <th>
                    Country
                </th>
            </tr>
            <tr style="color: red">
                <td align="center">
                     <img src="http://localhost:3367/UploadFile/Pakiza.png" class="test"alt="" height="100" width="120" align="middle" replace>
                       
                </td>
                <td>
                    Maria Anders
                </td>
                <td>
                    Germany
                </td>
            </tr>
            <tr>
                <td>
                    Centro comercial Moctezuma
                </td>
                <td>
                    Francisco Chang
                </td>
                <td>
                    Mexico
                </td>
            </tr>
            <tr>
                <td>
                    Ernst Handel
                </td>
                <td>
                    Roland Mendel
                </td>
                <td>
                    Austria
                </td>
            </tr>
            <tr>
                <td>
                    Island Trading
                </td>
                <td>
                    Helen Bennett
                </td>
                <td>
                    UK
                </td>
            </tr>
            <tr>
                <td>
                    Laughing Bacchus Winecellars
                </td>
                <td>
                    Yoshi Tannamuri
                </td>
                <td>
                    Canada
                </td>
            </tr>
            <tr>
                <td>
                    Magazzini Alimentari Riuniti
                </td>
                <td>
                    Giovanni Rovelli
                </td>
                <td>
                    Italy
                </td>
            </tr>
        </table>
        <div>
            <br />
            <br />
            <br />
            <table class="im44" style="text-align: center">
                <tr style="background-color: #e8eef4">
                    <td>
                        Checked by
                    </td>
                </tr>
                <tr>
                    <td>
                        Kazi Shakhawat Hossain
                    </td>
                </tr>
            </table>
        </div>
        </div>
        <table class="im44">
        <tr>
        <td class="col-sm-12 col-md-3 col-lg-3">
        test purposes
        </td >
       
        <td align="left" >
         <img src="http://localhost:3367/UploadFile/Footer1.jpg" alt="" ;height="40"; width="50" ; replace>
        </td>
        <td align="right">
            <img src="http://localhost:3367/UploadFile/Footer2.jpg" alt="" height="40" width="50"  replace>
        </td>
        </tr>
        </table>
   </div>     
    </div>
</body>
</html>
@using (Html.BeginForm("ExportPDF", "Class", FormMethod.Post))
{
    <input type="hidden" name="GridHtml2" />
    <input type="submit" id="btnSubmit" value="Export2" />
}
<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml2']").val($("#Grid").html());
            //            $("#GridHtml").val($("#Grid").html());
        });
    });
</script>

DAY_ONE/Views/Class/HtmltoPDF2.cshtml
@{
    ViewBag.Title = "HtmltoPDF2";
}

<h2>HtmltoPDF2</h2>

DAY_ONE/Views/Class/HtmltoPDF3.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="../../css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="Grid" >
    <style>
        .BG
        {
            background-image:url(http://localhost:3367/UploadFile/BG2.jpg);
            opacity:0.5;
        }
    </style>
        <div class="BG" >
            @* <input type="text" id="GridHtml3" name="GridHtml7" />*@ @* <div class="testdiv">*@
            <img src="http://localhost:3367/UploadFile/Pakiza.png" alt="" id="imgs" runat="server"
                replace>
            <p style="text-align: right; font-weight:bold; color: black;">
                Kazi Shakhawat Hossain
                <br />
                Business Automation<br />
                Pakiza Technovation Limited.
            </p>
            <h5 style="color: Black; text-align: center ;border-collapse: collapse;">
                Company's Information
            </h5>
        </div>
        <table border="1">
            <tr>
                <td style="background-color:Green; color:white">
                    Company
                </td>
                <td>
                    Contact
                </td>
                <td>
                    Country
                </td>
            </tr>
            <tr>
                <td>
                    Alfreds Futterkiste
                </td>
                <td>
                    Maria Anders
                </td>
                <td>
                    Germany
                </td>
            </tr>
            <tr>
                <td>
                    Centro comercial Moctezuma
                </td>
                <td>
                    Francisco Chang
                </td>
                <td>
                    Mexico
                </td>
            </tr>
            <tr>
                <td>
                    Ernst Handel
                </td>
                <td>
                    Roland Mendel
                </td>
                <td>
                    Austria
                </td>
            </tr>
            <tr>
                <td>
                    Island Trading
                </td>
                <td>
                    Helen Bennett
                </td>
                <td>
                    UK
                </td>
            </tr>
            <tr>
                <td>
                    Laughing Bacchus Winecellars
                </td>
                <td>
                    Yoshi Tannamuri
                </td>
                <td>
                    Canada
                </td>
            </tr>
            <tr>
                <td>
                    Magazzini Alimentari Riuniti
                </td>
                <td>
                    Giovanni Rovelli
                </td>
                <td>
                    Italy
                </td>
            </tr>
        </table>
    </div>
</body>
</html>
@using (Html.BeginForm("ExportPDF", "Class", FormMethod.Post))
{
    <input type="hidden" name="GridHtml2" />
    <input type="submit" id="btnSubmit" value="Export2" />
}
<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml2']").val($("#Grid").html());
            //            $("#GridHtml").val($("#Grid").html());
        });
    });
</script>

DAY_ONE/Views/Class/HtmltoPDFBG.cshtml
@{
    ViewBag.Title = "HtmltoPDFBG";
}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div id="Grid">
        <style>
            #imgLogo
            {
                height: 50px;
                width: 90px;
            }
            #imgHead
            {
                height: 200px;
                width: 600px;
            }
            #imgTable
            {
                height: 30px;
                width: 30px;
            }
            
            #imgFooter1
            {
                height: 50px;
                width: 90px;
            }
            
            table
            {
                width: 100%;
            }
            tr
            {
                text-align: center;
            }
            .row
            {
                display: flex;
            }
            
            .column
            {
                flex: 33.33%;
                padding: 5px;
            }
            .BG
            {
                background-color: Green;
                height: 1000px;
               
                
                
            }
            .data
            {
                background-color: #daedf4;
            }
        </style>
        <div class="BG" >
            <br />
            <div class="data">
                @* <input type="text" id="GridHtml3" name="GridHtml7" />*@ @* <div class="testdiv">*@
                <img src="http://localhost:3367/UploadFile/evaly.jpg" alt="" id="imgLogo" runat="server"
                    replace> <br />
                <p style="text-align: center; font-weight: bold; color: black;">
                    <img src="http://localhost:3367/UploadFile/BD.jpg" alt="" id="imgHead" runat="server"
                        replace>
                </p>
                <h3 style="color: Green; text-align: center; font-weight: bold">
                    POINTS TABLE</h3>
                <p style="color: Black; text-align: center; font-weight: bold">
                    ICC World Cup Super League 2020 - 2020/23
                </p>
                <table border="1">
                    <tr style="background-color: Green; color: white">
                        <td>
                            Flag
                        </td>
                        <td style="background-color: Green; color: white">
                            TEAM NAME
                        </td>
                        <td>
                            MTS
                        </td>
                        <td>
                            WIN
                        </td>
                        <td>
                            LOSS
                        </td>
                        <td>
                            POINT
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/Ban.jpg" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            BAN
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/India.jpg" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            India
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/Aus.jpg" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            Australia
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/England.jpg" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            England
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/NZ.png" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            New Zealand
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/Pak.png" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            Pakistan
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="http://localhost:3367/UploadFile/WI.png" alt="" id="imgTable" runat="server"
                                replace>
                        </td>
                        <td>
                            West Indies
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            5
                        </td>
                        <td>
                            3
                        </td>
                        <td>
                            50
                        </td>
                    </tr>
                </table>
                </div>
                 <br />
                <br />
                <br />
                <br />
                 <br />
                <br />
                <br />
                <br />
                 <br />
                <br />
                <br />
                <br />
            <table>
                    <tr>
                        <td class="col-sm-6 col-md-6 col-lg-6" style="text-align: center">
                            <img src="http://localhost:3367/UploadFile/icc.jpg" alt="" id="imgFooter1" runat="server"
                                replace>
                        </td>
                        <td class="col-sm-6 col-md-6 col-lg-6" style="text-align: center">
                            <img src="http://localhost:3367/UploadFile/GTV.png" alt="" id="imgFooter1" runat="server"
                                replace>
                        </td>
                    </tr>
                </table>
        </div>
        <footer>
  <p style="text-align:left;font-weight: bold; color:Green">International Cricket Council. icc-cricket.com.</p>
  <p></p>
</footer>
    </div>
</body>
</html>
@using (Html.BeginForm("ExportPDF", "Class", FormMethod.Post))
{
    <input type="hidden" name="GridHtml2" />
    <input type="submit" id="btnSubmit" value="Export2" />
}
<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml2']").val($("#Grid").html());
            //            $("#GridHtml").val($("#Grid").html());
        });
    });
</script>